version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: mealtracker
      MYSQL_ROOT_PASSWORD: 8&pqA24iyQ01
      MYSQL_ROOT_HOST: '%'
      TZ: UTC
    ports:
      - "13307:3306"

  webapi:
    image: tmhung/mealtracker:0.0.1-SNAPSHOT
    environment:
      TZ: UTC
    ports:
      - "9001:9000"
    depends_on:
      - db
