spring:
  datasource:
    url: jdbc:mysql://localhost:13306/mealtracker?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=UTC
    username: root
    password: 8&pqA24iyQ01

logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE
